API_KEY: ENC[AES256_GCM,data:2b8/Duk=,iv:AtrKFYjOeIP0qXJgMqkYeH9wlLZT6wTTJREbG9mTKT8=,tag:Q9fjArF6oD/RxgFNWbSb6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-04T19:39:53Z"
    mac: ENC[AES256_GCM,data:ek+f7N9otBP+PV56N1kGe/lIGDKUU5VWwS32bozbfbYh08Rgx9ePNHvgoRIlGvFfBC8Lj6uGWOyqMPwwvSzDTrfT3lQs7kPFI4G+5d2cxb9iiA3MR8AT+K6w3gg8B1GV1E6Dgfmg/319lQwRbmnIY2dzqpDQxu72zAk1Y7xRoOs=,iv:eb5NrenGrxnNh+mr9hmSANJEdonSS9ZySqDQngWZGLI=,tag:+qdGyXjftq8vahuIU+9zfw==,type:str]
    pgp:
        - created_at: "2025-03-04T19:36:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DmG/MX+EbQZoSAQdAygRvGIqZSx5nkpdpeIgFvU4A/0/q3Us0FBJ9uqyht1kw
            f7tN9SJO/7jvdnKnQWFbTsiGvmuT7QQbVcgXSrGVbgg/18LQoqA15gLbbAiPnpVO
            1GgBCQIQc9jiNl2ntmOwO8fPJCF8rX38EsBAn+Uz1GY06CdhzOytxiMv9utQZ7fE
            4cZgsOD9x9F+KolPDrqXJXUwMLs1IVT1VG5r+KZnyPczKmk1UHzJFRJ7MdJyzfiF
            e+YzhLZTSWQ1wA==
            =Xqze
            -----END PGP MESSAGE-----
          fp: 91A2EE07E7669045137A7487A93DC0966B5E100A
    unencrypted_suffix: _unencrypted
    version: 3.9.4
