name: CI Pipeline for Python Web Appplication

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/app_python.yml"
      - "app_python/**"

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Linter
        run: |
          make check

      - name: Run Tests
        run: |
          make test

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./app_python/coverage.json
